resilience4j.circuitbreaker:
  instances:
    orderProcess:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50

spring:
  retry:
    retryable:
      enabled: true
    backoff:
      delay: 2000
      maxDelay: 10000
      multiplier: 1.5
    maxAttempts: 3